import { notFound } from 'next/navigation';
import { getLP } from '@/lib/data';
import Renderer from '@/components/lp/Renderer';

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  const lp = await getLP(slug);

  if (!lp) return { title: 'Page Not Found' };

  // Assume the first block title is the meta title
  const title = lp.content.blocks.find(b => b.type === 'hero')?.data.title || lp.slug;

  return {
    title: `${title} | Live LP`,
    description: 'Generated by Landing Page Factory',
  };
}

export default async function DynamicLP({ params }: PageProps) {
  const { slug } = await params;
  const lp = await getLP(slug);

  if (!lp) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-white">
      <Renderer blocks={lp.content.blocks} />
      <footer className="py-12 border-t border-slate-50 bg-white text-center">
         <p className="text-[10px] font-black text-slate-300 uppercase tracking-[0.3em]">
           Powered by WINDRE LP Builder
         </p>
      </footer>
    </main>
  );
}
